{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "bisheng.componentLabels" (dict "component" "redis" "context" $) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    {{- include "bisheng.componentSelectorLabels" (dict "component" "redis" "context" $) | nindent 4 }}
{{- end }}
