{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "bisheng.componentFullname" (dict "component" "redis" "context" $) }}
  labels:
    {{- include "bisheng.componentLabels" (dict "component" "redis" "context" $) | nindent 4 }}
spec:
  serviceName: redis
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      {{- include "bisheng.componentSelectorLabels" (dict "component" "redis" "context" $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bisheng.componentSelectorLabels" (dict "component" "redis" "context" $) | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: {{ include "bisheng.image" (dict "image" .Values.redis.image "context" $) }}
          command: ["redis-server", "/etc/redis.conf"]
          env:
            - name: TZ
              value: {{ .Values.global.timezone | quote }}
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/redis.conf
              subPath: redis.conf
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: config
          configMap:
            name: {{ include "bisheng.componentFullname" (dict "component" "redis" "context" $) }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- include "bisheng.storageClass" . | nindent 8 }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}
{{- end }}
