{{- if .Values.elasticsearch.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "bisheng.componentFullname" (dict "component" "elasticsearch" "context" $) }}
  labels:
    {{- include "bisheng.componentLabels" (dict "component" "elasticsearch" "context" $) | nindent 4 }}
spec:
  serviceName: elasticsearch
  replicas: {{ .Values.elasticsearch.replicaCount }}
  selector:
    matchLabels:
      {{- include "bisheng.componentSelectorLabels" (dict "component" "elasticsearch" "context" $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bisheng.componentSelectorLabels" (dict "component" "elasticsearch" "context" $) | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: elasticsearch
          image: {{ include "bisheng.image" (dict "image" .Values.elasticsearch.image "context" $) }}
          env:
            - name: TZ
              value: {{ .Values.global.timezone | quote }}
            - name: xpack.security.enabled
              value: "false"
            - name: discovery.type
              value: single-node
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
            - name: transport
              containerPort: 9300
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /bitnami/elasticsearch/data
          resources:
            {{- toYaml .Values.elasticsearch.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- include "bisheng.storageClass" . | nindent 8 }}
        resources:
          requests:
            storage: {{ .Values.elasticsearch.persistence.size }}
{{- end }}
