apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bisheng.componentFullname" (dict "component" "backend" "context" $) }}
  labels:
    {{- include "bisheng.componentLabels" (dict "component" "backend" "context" $) | nindent 4 }}
data:
  config.yaml: |
    database_url: "mysql+pymysql://root:gAAAAABlp4b4c59FeVGF_OQRVf6NOUIGdxq8246EBD-b0hdK_jVKRs1x4PoAn0A6C5S6IiFKmWn0Nm5eBUWu-7jxcqw6TiVjQA==@mysql:3306/bisheng?charset=utf8mb4"
    redis_url: "redis://redis:6379/1"
    celery_redis_url: "redis://redis:6379/2"
    celery_task:
      task_routers:
        bisheng.worker.knowledge.*:
          queue: knowledge_celery
        bisheng.worker.workflow.*:
          queue: workflow_celery
    vector_stores:
      milvus:
        connection_args: !env ${BS_MILVUS_CONNECTION_ARGS}
        is_partition: !env ${BS_MILVUS_IS_PARTITION}
        partition_suffix: !env ${BS_MILVUS_PARTITION_SUFFIX}
      elasticsearch:
        url: !env ${BS_ELASTICSEARCH_URL}
        ssl_verify: !env ${BS_ELASTICSEARCH_SSL_VERIFY}
    object_storage:
      type: minio
      minio:
        schema: !env ${BS_MINIO_SCHEMA}
        cert_check: !env ${BS_MINIO_CERT_CHECK}
        endpoint: !env ${BS_MINIO_ENDPOINT}
        sharepoint: !env ${BS_MINIO_SHAREPOINT}
        access_key: !env ${BS_MINIO_ACCESS_KEY}
        secret_key: !env ${BS_MINIO_SECRET_KEY}
        public_bucket: 'bisheng'
        tmp_bucket: 'tmp-dir'
    environment:
      env: dev
      uns_support: ['png','jpg','jpeg','bmp','doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'txt', 'md', 'html', 'pdf', 'csv', 'tiff']
    logger_conf:
      level: {{ .Values.backend.config.logLevel | quote }}
      format: '<level>[{time:YYYY-MM-DD HH:mm:ss.SSSSSS}] [{level.name} process-{process.id}-{thread.id} {name}:{line}]</level> - <level>trace={extra[trace_id]} {message}</level>'
      handlers:
        - sink: "/app/data/bisheng.log"
          level: INFO
          format: '<level>[{time:YYYY-MM-DD HH:mm:ss.SSSSSS}] [{level.name} process-{process.id}-{thread.id} {name}:{line}]</level> - <level>trace={extra[trace_id]} {message}</level>'
          rotation: "00:00"
          retention: "3 Days"
          enqueue: ture
        - sink: "/app/data/statistic.log"
          level: INFO
          filter: "lambda record: record['level'].name == 'INFO' and record['message'].startswith('k=s')"
          format: "[{time:YYYY-MM-DD HH:mm:ss.SSSSSS}]|{level}|BISHENG|{extra[trace_id]}||{process.id}|{thread.id}|||#EX_ERR:POS={name},line {line},ERR=500,EMSG={message}"
          rotation: "00:00"
          retention: "3 Days"
          enqueue: ture
  entrypoint.sh: |
    #!/bin/bash
    set -xe
    export PYTHONPATH="./"

    start_mode=${1:-api}

    start_knowledge(){
      celery -A bisheng.worker.main worker -l info -c 20 -P threads -Q knowledge_celery -n knowledge@%h
    }

    start_workflow(){
      celery -A bisheng.worker.main worker -l info -c 100 -P threads -Q workflow_celery -n workflow@%h
    }

    start_beat(){
      celery -A bisheng.worker.main beat -l info
    }

    start_linsight(){
      python bisheng/linsight/worker.py --worker_num 4 --max_concurrency 5
    }

    start_default(){
      celery -A bisheng.worker.main worker -l info -c 100 -P threads -Q celery -n celery@%h
    }

    if [ "$start_mode" = "api" ]; then
      echo "Starting API server..."
      uvicorn bisheng.main:app --host 0.0.0.0 --port 7860 --no-access-log --workers 8
    elif [ "$start_mode" = "knowledge" ]; then
      echo "Starting Knowledge Celery worker..."
      start_knowledge
    elif [ "$start_mode" = "workflow" ]; then
      echo "Starting Workflow Celery worker..."
      start_workflow
    elif [ "$start_mode" = "beat" ]; then
      echo "Starting Celery beat..."
      start_beat
    elif [ "$start_mode" = "default" ]; then
      echo "Starting default celery worker..."
      start_default
    elif [ "$start_mode" = "linsight" ]; then
      echo "Starting LinSight worker..."
      start_linsight
    elif [ "$start_mode" = "worker" ]; then
      echo "Starting All worker..."
      start_knowledge &
      start_workflow &
      start_linsight &
      start_default &
      start_beat
      echo "All workers started successfully."
    else
      echo "Invalid start mode. Use api、worker、knowledge、workflow、beat、default、linsight."
      exit 1
    fi
