apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bisheng.componentFullname" (dict "component" "backend" "context" $) }}
  labels:
    {{- include "bisheng.componentLabels" (dict "component" "backend" "context" $) | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- include "bisheng.storageClass" . | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
