apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "bisheng.componentLabels" (dict "component" "frontend" "context" $) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
    - name: websocket
      port: 8443
      targetPort: 8443
      protocol: TCP
  selector:
    {{- include "bisheng.componentSelectorLabels" (dict "component" "frontend" "context" $) | nindent 4 }}
